### ISSUE TITLE
Do not fix french quotes that are already ok

### ISSUE THREAD

**Issue by borisschapira** [borisschapira/jekyll-microtypo#1]
## Issue

Input: `«&nbsp;test&nbsp;»` or `« test »` (with real non-breaking space)
Expected: `«&#8239;test&#8239;»`
Real : `« &nbsp;test&nbsp; »`
## TODO
- [x] Write test
- [x] Fix

**Comment by nhoizey** [comment]
My Markdown contains a real non brackable space, not a `&nbsp;`, where/when is it converted?

**Comment by borisschapira** [comment]
Issue updated. To investigate.

**Comment by nhoizey** [comment]
Yes, thanks!
