### ISSUE TITLE
Do not modify inline JavaScript code

### ISSUE THREAD

**Issue by nhoizey** [borisschapira/jekyll-microtypo#2]
I have the issue on this page: https://nicolas-hoizey.com/recherche.html

![microtypo-js-code](https://cloud.githubusercontent.com/assets/78213/17986488/310e7460-6b1b-11e6-8a80-42894d145e2f.png)

**Comment by borisschapira** [comment]
v0.0.5 should fix your issue. Tell me!

**Comment by nhoizey** [comment]
I have another issue now, don't know yet if it's because of microtypo…

https://nicolas-hoizey.com/recherche.html

**Comment by borisschapira** [comment]
Seems like it is. I'll look right now.

**Comment by borisschapira** [comment]
Both your [jQuery](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_assets/javascripts/vendors/jquery-3.1.0.js#L9456) and [AlgoliasearchLite](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_assets/javascripts/vendors/algoliasearchLite-3.18.0.js#L3252) contains the `<script>` string.
As [you inline them](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_includes/recherche.html#L18) with Jekyll Assets, it makes it difficult for jekyll-microtypo to ignore script tag with [this simplest parsing strategy](https://github.com/borisschapira/jekyll-microtypo/blob/master/lib/jekyll/microtypo.rb#L23) 😞

**Comment by nhoizey** [comment]
I understand it's not easy.

It would be nice to have a way to prevent parsing of a fragment of our pages, anyway.

Maybe HTML comments like `<!-- nomicrotypo -->` and `<!-- endnomicrotypo -->`.

**Comment by nhoizey** [comment]
A quick fix for my own need:
https://github.com/nhoizey/nicolas-hoizey.com/commit/067cdb5302aea2564f3dda6ec121e6dc27a6a809

**Comment by nhoizey** [comment]
Fixed thanks to #3 

I also had this issue with inline CSS, by the way:
![2016-08-30 at 16 55](https://cloud.githubusercontent.com/assets/78213/18095960/f1e9a7f2-6ed8-11e6-8d4e-fa374090ee66.png)

**Comment by borisschapira** [comment]
Ignore code section comments are now available and documented: https://github.com/borisschapira/jekyll-microtypo#ignore-code-sections
