### ISSUE TITLE
Add a specific comment to define a no-fix area

### ISSUE THREAD

**Issue by borisschapira** [borisschapira/jekyll-microtypo#3]
Every content between  and  should be left as it is.

**Comment by borisschapira** [comment]
Fixed by https://github.com/borisschapira/jekyll-microtypo/commit/3636efb976ea6f8bf1ec6a921ca7d8489cead786

**Comment by borisschapira** [comment]
ping @nhoizey, feature is available in v0.0.6.

**Comment by nhoizey** [comment]
Great!
