### ISSUE TITLE
Avoid creating a new config hash at each call of the filter

### ISSUE THREAD

**Issue by DirtyF** [borisschapira/jekyll-microtypo#6]
```gherkin
Given I use the microtypo filter on a single layout
When I build the site
Then a duplicate configuration hash is created by microtypo
And "Configuration file: /Users/frank/code/frank.taillandier.me/_config.yml" line is displayed twice in the ouput:
```

```sh
bundle exec jekyll build
Configuration file: /Users/frank/code/frank.taillandier.me/_config.yml
            Source: /Users/frank/code/frank.taillandier.me
       Destination: /Users/frank/code/frank.taillandier.me/_site
 Incremental build: disabled. Enable with --incremental
      Generating...

Configuration file: /Users/frank/code/frank.taillandier.me/_config.yml
                    done in 6.87 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

This could be avoided by using the `context.registers `feature of Liquid at `context.registers[:site]`. 
We can access the global configuration file `_config.yml` using `context.registers[:site].config` instead of `Jekyll.configuration({})`

Current tests will need to [mockup a Jekyll site](https://github.com/jekyll/jekyll/blob/e0f500118219b0e819520bd7bd1aeb4695e31cba/test/test_filters.rb#L26-L31) in order to pass.

In Jekyll a context is created in the filters tests: 
https://github.com/jekyll/jekyll/blob/master/test/test_filters.rb#L12

This is a minor issue, but every time you use this filter, the plugin will create a new instance of a Jekyll configuration.

**Comment by borisschapira** [comment]
TBH, I tried to fix that but didn't succeed. If s.o. can help, would be appreciated.

**Comment by ashmaroli** [comment]
@borisschapira I see 6 method definitions in the `Jekyll::Microtypo` module. Did you intend for all of those methods to be `public`?

**Comment by borisschapira** [comment]
Oh, good point. I just commited eddb4d9f750aa093dc6a64f08d78652ba36d8c57 for this, thanks.

**Comment by ashmaroli** [comment]
Awesome. Coming onto the issue at hand, all *Liquid::Filters* have access to the current `context`.

Therefore, you can easily get current `site` by using `@context.registers[:site]` and therefore `@context.registers[:site].config['microtypo']`. But unfortunately, the test-suite doesn't generate a mock context so you won't be able to test it via `rake`
