### ISSUE TITLE
Avoid modifying URLs

### ISSUE THREAD

**Issue by nhoizey** [borisschapira/jekyll-microtypo#7]
It would be great if the plugin recognized URLs and didn't change them.

Example: https://twitter.com/nhoizey/status/984395093401657344

The URL contains a sequence of numbers followed by a "e":

```
https://webmention.io/avatar/pbs.twimg.com/…a15642e.jpg
```

The "e" is transformed as if it was a French ordinal number:

```
https://webmention.io/avatar/pbs.twimg.com/…a15642<sup>e</sup>.jpg
```

**Comment by DirtyF** [comment]
FWIW, Jekyll relies on `adressable` for validating URLs

https://github.com/jekyll/jekyll/blob/2765f0fcb998b26241ec0f512f789586ee98b679/lib/jekyll/commands/doctor.rb#L146-L155

**Comment by borisschapira** [comment]
@DirtyF: You certainly had an intellectual trajectory in mind when you shared that, but right now, I don't see it. Enlighten me, please! ;)

**Comment by nhoizey** [comment]
Just got a new issue with this ordinal number regex.

My CSS is computed into this URL:
`https://nicolas-hoizey.com/assets/components/footer-c73885d83bce23c897e4cb9831e0733eedcf64c3d6655782b3a898b53e15831e.css`

Which is transformed into this:
`https://nicolas-hoizey.com/assets/components/footer-c73885d83bce23c897e4cb9831e0733eedcf64c3d6655782b3a898b53e15831<sup>e</sup>.css`

I guess the regex could at least ignore `(\d)e` when there is a letter before.

A lot of hexadecimal values can end with a number and an `e`.

**Comment by borisschapira** [comment]
Thanks for the idea, @nhoizey. Your issues should be fixed by 1992c061ba0f8b585315a1551da379cd94a8496f, (v0.2.4). Could you confirm?

**Comment by nhoizey** [comment]
It works indeed! 👍🏻

**Comment by nhoizey** [comment]
BTW, you could also authorize punctuation marks.

**Comment by borisschapira** [comment]
What do you mean?

**Comment by nhoizey** [comment]
It looks like your regex won't find the ordinal in something like `blah blah,35e item`

**Comment by borisschapira** [comment]
> It looks like your regex won't find the ordinal in something like `blah blah,35e item`

You're right. A space is required before the ordinal. Is it an issue?

**Comment by nhoizey** [comment]
This is not an issue for me, as I always put a space after a comma, but it might be an issue if people write `blah blah,35e item`.

I checked, and the plugin currently doesn't add the space after the comma, I guess because some commas are decimal separator and should not be followed by a space.

Is it possible to have French decimal ordinal numbers, like `j'ai pris le 23,76e`?

**Comment by borisschapira** [comment]
Decimal ordinals, is that a thing?!

**Comment by nhoizey** [comment]
It looks like [they are a thing](https://www.brighthubeducation.com/esl-lesson-plans/59563-fraction-decimal-ordinal-basics/#ezoic-pub-ad-placeholder-107), but I don't think they have a notation with `<sup>`.

But someone could write this in French: `j'avais bu mon verre,3e du repas,avant de manger`.

It's up to you to decide if the plugin should also deal with such punctuation marks issues.
