### ISSUE TITLE
Adds `&nbsp;` in inline CSS

### ISSUE THREAD

**Issue by nhoizey** [borisschapira/jekyll-microtypo#8]
I've got this CSS inline in my pages:

```
margin: 0 0 calc(0.9rem + 0.5vw);
```

The plugin changes it to this:

```
margin: 0 0&nbsp;calc(0.9rem + 0.5vw);
```

Which obviously doesn't work… 😅

I guess it's because there is a number followed by a space and a letter, like if it was a unit.

**Comment by borisschapira** [comment]
Isn't this the same issue as https://github.com/borisschapira/jekyll-microtypo/issues/2 ?

**Comment by borisschapira** [comment]
Also, if your inline CSS is inside `<pre>` tags, it should not be "fixed". Is it? If so, could you provide the markup?

**Comment by nhoizey** [comment]
I guess it is indeed, and I used the comment as a temporary fix, but it looks like I will keep it!

Sorry for the missed opportunity to learn from the past… 😅

**Comment by nhoizey** [comment]
Just saw your second comment. My code is not in `<pre>` tags.

**Comment by nhoizey** [comment]
I guess it will be safer to also use the comment when I inline CSS or JS with Jekyll Assets:

```
<!-- nomicrotypo -->
{% asset "components/navigation" @inline %}
<!-- endnomicrotypo -->
```

**Comment by borisschapira** [comment]
If I excluded code between `<code>` tags, would that help? I wonder why I did not do it sooner…

**Comment by nhoizey** [comment]
No, my code is not in `<code>` either.

Could you exclude code between `<style>` and `<script>` tags?

**Comment by borisschapira** [comment]
New version 1.1.0 excludes `<code`=>`</code>` and `<style`=>`</style>` in addition to `<script`=>`</script>`

**Comment by nhoizey** [comment]
It works! 👍
